language: node_js
node_js:
    - stable

script:
  - yarn
  - yarn builds
  - cp ./build/index.html ./build/200.html
#  - cp -r /home/travis/build/odeum/odeum-codejs/experiments/3/build ../../

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: web/odeum
  bucket: w3odeum
  region: eu-west-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: w3odeum
  key: latest.zip
  bundle_type: zip
  application: odeumapp
  deployment_group: teamodeum
  region: eu-west-1
  on: *2

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
